create database RUANGBACA;

SHOW databases;

use RUANGBACA;

CREATE TABLE RUANGBACA.ANGGOTA (
  KODE_ANGGOTA VARCHAR(15) NOT NULL,
  PROGRAM_STUDI_KODE_PROGRAM_STUDI SMALLINT UNSIGNED NOT NULL,
  NAMA VARCHAR(45),
  PRIMARY KEY(KODE_ANGGOTA)
);
CREATE TABLE RUANGBACA.ANGGOTA_KONTAK (
  ANGGOTA_KODE_ANGGOTA VARCHAR(15) NOT NULL,
  NO_HP VARCHAR(15) NOT NULL,
  UNIQUE INDEX UQ(NO_HP, ANGGOTA_KODE_ANGGOTA),
  INDEX ANGGOTA_KOMTAK_FKIndex1(ANGGOTA_KODE_ANGGOTA)
);
CREATE TABLE RUANGBACA.MAHASISWA (
  NIM VARCHAR(15) NOT NULL,
  ANGGOTA_KODE_ANGGOTA VARCHAR(15) NOT NULL,
  SELEKSI_MASUK_ID_SELEKSI_MASUK SMALLINT UNSIGNED NOT NULL,
  ANGKATAN SMALLINT UNSIGNED NULL,
  PRIMARY KEY(NIM),
  INDEX MAHASISWA_FKIndex1(SELEKSI_MASUK_ID_SELEKSI_MASUK),
  INDEX MAHASISWA_FKIndex2(ANGGOTA_KODE_ANGGOTA)
);
CREATE TABLE RUANGBACA.SELEKSI_MASUK (
  ID_SELEKSI_MASUK SMALLINT UNSIGNED NOT NULL,
  SELEKSI_MASUK VARCHAR(45) NULL,
  PRIMARY KEY(ID_SELEKSI_MASUK)
);
CREATE TABLE RUANGBACA.DOSEN (
  NIP VARCHAR(25) NOT NULL,
  ANGGOTA_KODE_ANGGOTA VARCHAR(15) NOT NULL,
  PRIMARY KEY(NIP),
  INDEX DOSEN_FKIndex1(ANGGOTA_KODE_ANGGOTA)
);
CREATE TABLE RUANGBACA.FAKULTAS (
  KODE_FAKULTAS SMALLINT UNSIGNED NOT NULL,
  FAKULTAS VARCHAR(45) NULL,
  PRIMARY KEY(KODE_FAKULTAS)
);
CREATE TABLE RUANGBACA.DEPARTEMEN (
  KODE_DEPARTEMEN SMALLINT UNSIGNED NOT NULL,
  FAKULTAS_KODE_FAKULTAS SMALLINT UNSIGNED NOT NULL,
  DEPARTEMEN VARCHAR(45) NULL,
  PRIMARY KEY(KODE_DEPARTEMEN),
  INDEX DEPARTEMEN_FKIndex1(FAKULTAS_KODE_FAKULTAS)
);
CREATE TABLE RUANGBACA.STRATA (
  ID_STRATA SMALLINT UNSIGNED NOT NULL,
  STRATA VARCHAR(25) NULL,
  PRIMARY KEY(ID_STRATA)
);
CREATE TABLE RUANGBACA.PROGRAM_STUDI (
  KODE_PROGRAM_STUDI SMALLINT UNSIGNED NOT NULL,
  DEPARTEMEN_KODE_DEPARTEMEN SMALLINT NOT NULL,
  STRATA_ID_STRATA SMALLINT UNSIGNED NOT NULL,
  PROGRAM_STUDI VARCHAR(45) NULL,
  PRIMARY KEY(KODE_PROGRAM_STUDI),
  INDEX PROGRAM_STUDI_FKIndex1(STRATA_ID_STRATA),
  INDEX PROGRAM_STUDI_FKIndex2(DEPARTEMEN_KODE_DEPARTEMEN)
);
CREATE TABLE RUANGBACA.PETUGAS (
  KODE_PETUGAS VARCHAR(10) NOT NULL,
  NAMA VARCHAR(10) NULL,
  USERNAME VARCHAR(10) NULL,
  PASSWORD  VARCHAR(45) NULL,
  PRIMARY KEY(KODE_PETUGAS),
  UNIQUE INDEX UQ_PETUGAS(PASSWORD )
);
CREATE TABLE RUANGBACA.TRANSAKSI (
  KODE_TRANSAKSI VARCHAR(10) NOT NULL,
  PETUGAS_KODE_PETUGAS VARCHAR(10) NOT NULL,
  ANGGOTA_KODE_ANGGOTA VARCHAR(15) NOT NULL,
  WAKTU_TANSAKSI TIMESTAMP NULL,
  PRIMARY KEY(KODE_TRANSAKSI),
  INDEX TRANSAKSI_FKIndex1(ANGGOTA_KODE_ANGGOTA),
  INDEX TRANSAKSI_FKIndex2(PETUGAS_KODE_PETUGAS),
  UNIQUE INDEX UQ_TRANSAKSI(ANGGOTA_KODE_ANGGOTA, WAKTU_TANSAKSI)
);
CREATE TABLE RUANGBACA.BUKU (
  KODE_BUKU VARCHAR(10) NOT NULL,
  JUDUL VARCHAR(10) NULL,
  PENERBUT VARCHAR(45) NULL,
  TEMPAT_TERBIT VARCHAR(45) NULL,
  PRIMARY KEY(KODE_BUKU)
);
CREATE TABLE RUANGBACA.PENGARANG (
  PENGARANG VARCHAR(45) NOT NULL,
  KODE_BUKU VARCHAR(10) NOT NULL,
  PRIMARY KEY(PENGARANG, KODE_BUKU),
  INDEX PENGARANG_FKIndex1(KODE_BUKU)
);
CREATE TABLE RUANGBACA.EKSEMPLAR (
  KODE_EKSEMPLAR VARCHAR(10) NOT NULL,
  BUKU_KODE_BUKU VARCHAR(10) NOT NULL,
  PRIMARY KEY(KODE_EKSEMPLAR),
  INDEX EKSEMPLAR_FKIndex1(BUKU_KODE_BUKU)
);
CREATE TABLE RUANGBACA.DETAIL_TRANSAKSI (
  WAKTU_PINJAM TIMESTAMP NOT NULL,
  EKSEMPLAR_KODE_EKSEMPLAR VARCHAR(10) NOT NULL,
  TRANSAKSI_KODE_TRANSAKSI VARCHAR(10) NOT NULL,
  WAKTU_KEMBALI TIMESTAMP NULL,
  WAKTU_WAJIB_KEMBALI TIMESTAMP NULL,
  PRIMARY KEY(WAKTU_PINJAM, EKSEMPLAR_KODE_EKSEMPLAR, TRANSAKSI_KODE_TRANSAKSI),
  INDEX DETAIL_TRANSAKSI_FKIndex1(EKSEMPLAR_KODE_EKSEMPLAR),
  INDEX DETAIL_TRANSAKSI_FKIndex2(TRANSAKSI_KODE_TRANSAKSI)
);
